# Generated by Django 3.2.4 on 2021-09-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selcorshop', '0003_auto_20210902_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='subcategory',
        ),
    ]
